
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: bde-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: bde-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  # The Speed Layer: Vitals Data Producer
  vitals-producer:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: bde-vitals-producer
    command: ["python", "../backend/streaming/vitals_producer.py"]
    volumes:
      - data-volume:/app/backend/data
    depends_on:
      - kafka

  # The Serving Layer: FastAPI Backend
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: bde-fastapi
    ports:
      - "8000:8000"
    env_file:
      - api/.env
    volumes:
      - data-volume:/app/backend/data
      - mock-data-volume:/app/api/mock_data
    depends_on:
      - kafka
      - vitals-producer

  # The Presentation Layer: React/Nginx Frontend
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: bde-frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  data-volume:
  mock-data-volume:
